### ISSUE TITLE
Nicer cart model

### ISSUE THREAD

**Issue by tobyplowy** [cyian-1756/railtest#1]
I made a cart model maybe you like it if so I can make more variants 
This link shuld have the model it's a .b3d but you can also use the blend file aswell
https://github.com/D00Med/farlands/tree/master/mods/carts/models

**Comment by cyian-1756** [comment]
That is a much nicer model

> like it if so I can make more variants

If you could make more variants that would be awesome (I suck at blender).

**Comment by tobyplowy** [comment]
> If you could make more variants that would be awesome

Yes I could do that what variants do you whant?
Cart with chest?
Cart with engine?

**Comment by cyian-1756** [comment]
I was thinking a cart with a chest, cart with a engine and cart with technic battery box

**Comment by tobyplowy** [comment]
> technic battery box 

can you give me a screenshot of that?

> cart with a engine

Shuld I make it look like the front of a train?

**Comment by tobyplowy** [comment]
@cyian-1756 also a carts item texture
![carts item](https://user-images.githubusercontent.com/16853304/31035171-4faca22a-a567-11e7-934d-74ea49b09a26.png)

**Comment by tobyplowy** [comment]
@cyian-1756 
[chest cart.zip](https://github.com/cyian-1756/railtest/files/1345718/chest.cart.zip)
[cart train engine.zip](https://github.com/cyian-1756/railtest/files/1345720/cart.train.engine.zip)

**Comment by tobyplowy** [comment]
@cyian-1756  this is just a consept i hope you like it XD
[powercart.zip](https://github.com/cyian-1756/railtest/files/1345819/powercart.zip)

**Comment by tobyplowy** [comment]
@cyian-1756 can you also add my creddits to the page on the forums if there is any

**Comment by tobyplowy** [comment]
@cyian-1756  can you also add me in the README.MD Credits  sction

credit me as tobyplowy(aka toby109tt) for making the models and textures
they are licend under CC-BY-SA 3.0 UNPORTED.

**Comment by cyian-1756** [comment]
@tobyplowy 

> can you also add my creddits to the page on the forums if there is any

I haven't even made a forum post yet, I want to wait until the mod is stable (It more or less is right now) and I have a basic api written (I'm in the middle of that right now and should be done in a day or so)

>  can you also add me in the README.MD Credits sction

I'll do that right now

**Comment by cyian-1756** [comment]
@tobyplowy You've been added to the credits

**Comment by cyian-1756** [comment]
@tobyplowy 

[Here's](https://imgur.com/a/dJdiX) a screen shot of a technic battery box

**Comment by cyian-1756** [comment]
@tobyplowy I like the models you made, but could you reupload them exported into .b3d? I tried exporting the .blend files, but for some reason they're all very small in game (Less than 1/4 of a node). 

Sorry if this is some easily fixed thing I'm just not understanding, but I really suck at blender (It took me upwards of 10 minutes just to install a script to export to b3d)

**Comment by tobyplowy** [comment]
@cyian-1756 I can't export to b3d 

> just to install a script to export to b3d

Soooo you can do it?

**Comment by cyian-1756** [comment]
@tobyplowy I can but the scaling is all messed up. I'll google a bit and see if I can find out whats going wrong

**Comment by tobyplowy** [comment]
@cyian-1756 maybe you need to make the model bigger in blender before you export it?

**Comment by tobyplowy** [comment]
@cyian-1756 import the cart model and make sure the cart engine is the same size as the cart
You can export .b3d but can you import it aswell?

**Comment by cyian-1756** [comment]
@tobyplowy I can't import b3d, but trying to export the cart.blend file I ran into the same scale issue I'm getting with the other models. This leads me to believe there's something wrong with my set up

**Comment by tobyplowy** [comment]
@cyian-1756 I will ask a friend to help

@d00med i summon you with all power of XD
Please help

**Comment by cyian-1756** [comment]
@tobyplowy I tested with some other models from minetest mods and managed to export them at the right size, leading me to believe the scale if just off in these models and my set up is fine.

After some testing I've almost gotten the train engine model at the right pos/scale

**Comment by D00Med** [comment]
@tobyplowy @cyian-1756 I have been summoned xD What can I do?

**Comment by cyian-1756** [comment]
@D00Med I'm trying to export some .blend files to .b3d for use in minetest, but for the scale for them is pretty off (By like 200%) and I was wondering if you knew any way to auto-scale them so I wouldn't have to edit them all by hand

You can find the files I'm talking about a comments up in the thread

**Comment by tobyplowy** [comment]
@cyian-1756 he can do it D00med is used to fixing my mess by now XD

**Comment by cyian-1756** [comment]
![screenshot](https://user-images.githubusercontent.com/17493676/31049942-9b997776-a60c-11e7-901d-10d1480b5c13.png)

I've also run into this texturing issue. It appears on all the models at all scales (But the model above is one I've scaled by hand, not the originals already linked in the thread)

**Comment by D00Med** [comment]
@cyian-1756 I don't know any better way to do it unfortunately

**Comment by D00Med** [comment]
@cyian-1756 And the texture thing...did you crop it?

**Comment by cyian-1756** [comment]
@D00Med damn I'll get to scaling them then

And I didn't change the texture at all. It's exactly as it is in the .zip that was posted.

**Comment by D00Med** [comment]
@cyian-1756 Oh ok :/ sorry I'm not much help

**Comment by cyian-1756** [comment]
@D00Med It's fine. I needed to learn how to use blender anyway

**Comment by tobyplowy** [comment]
> I've also run into this texturing issue. It appears on all the models at all scales (But the model above is one I've scaled by hand, not the originals already linked in the thread)

That's happening becouse The Normals are inverted I will give you a fix for that tomorrow

**Comment by tobyplowy** [comment]
@cyian-1756 just go and edit the model in edit mode in blender than click on the mesh tab at the bottom than click normals and than select calculate outside that should fix it :)

**Comment by cyian-1756** [comment]
@tobyplowy Great! I'll get on that later on today

**Comment by tobyplowy** [comment]
@cyian-1756 yay if you can't fix it let me know so I can fix it tomorrow that's rufly 11 hours from now

**Comment by cyian-1756** [comment]
@tobyplowy I tried recalculating the outside normals and that didn't seem to fix it

**Comment by tobyplowy** [comment]
@cyian-1756 that's odd :/

**Comment by tobyplowy** [comment]
@cyian-1756 are you sure you selected the Faces before you did the recalculating?

In edit mode press A to select all and than recalculate the normals

**Comment by cyian-1756** [comment]
@tobyplowy 

> are you sure you selected the Faces before you did the recalculating

I did not

> In edit mode press A to select all and than recalculate the normals

I will

**Comment by tobyplowy** [comment]
@cyian-1756 in case you have already selected something press A to deselect all and A again to select everything :)

Also the train seems to be rotated wrong make sure the front is pointing to the front of the green arrow :)

**Comment by cyian-1756** [comment]
@tobyplowy 

I tried what you said and it still didn't work

I entered edit mode

Hit a

Clicked on Mesh/Normals/Recalculate Outside

Exported as b3d

The textures are still off

> Also the train seems to be rotated wrong make sure the front is pointing to the front of the green arrow :)

Nope it's right in the model, it's just wrong in that screen shot because I don't rotate the models in game yet

**Comment by tobyplowy** [comment]
> I tried what you said and it still didn't work

Huuuh I don't know whats wrong

**Comment by tobyplowy** [comment]
@cyian-1756 does this fix the problem?
[cart train engine.zip](https://github.com/cyian-1756/railtest/files/1346812/cart.train.engine.zip)

**Comment by cyian-1756** [comment]
@tobyplowy 

> Huuuh I don't know whats wrong

Same here (But I wouldn't rule out me making a simple mistake)

> does this fix the problem?

Yup! The textures work fine on that model

**Comment by tobyplowy** [comment]
@cyian-1756 yeh I just recalculated the Normals :/

Knowing how to do this is very important so you should prioritize it above all look for a tutorial on face normals (ignor all tutorials that have the name normal maps)

**Comment by cyian-1756** [comment]
> yeh I just recalculated the Normals :/

Damn, I musted made a mistake then

> Knowing how to do this is very important so you should prioritize it above all look for a tutorial on face normals (ignor all tutorials that have the name normal maps)

I will

**Comment by tobyplowy** [comment]
@cyian-1756 haha don't worry I used to have trouble understanding blender a year ago but d00med really helped me out also the tutorials on YouTube
